### ISSUE TITLE
Using command line arguments in an expected way always errors

### ISSUE THREAD

**Issue by lumaxis** [gorzell/folding-at-cloud#3]
When running `./start.sh` with an argument like `./start.sh --name my-folding`, it always shows an error:
```shell
$ ./start.sh -r westeurope
Unknown argument: -r. Use -h or --help for details on available arguments.
```

I ran into this with both `zsh` and `bash`.

**Comment by gorzell** [comment]
Bummer. I will take a look and see if I can fix this tonight.

**Comment by gorzell** [comment]
This should be resolved in https://github.com/gorzell/folding-at-cloud/commit/69f210811b596ccbaa56038666e62e8656b5d63d

**Comment by lumaxis** [comment]
Sweet, thanks!
